version: '2'

services:
  nginx:
    image: nginx:stable
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/ww/html/app
      - ./public:/var/www/html/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    links:
      - phalcon

  phalcon:
    # image: phalconphp/php-fpm:7-min
    build: ./docker/php/
    container_name: phalcon
    restart: always
    ports:
          - "9000:9000"
    volumes:
          - ./app:/var/www/html/app
          - ./public:/var/www/html/public
          - ./vendor:/var/www/html/vendor
          - ./composer.json:/var/www/html/composer.json

  redis:
      image: redis:alpine
      restart: always
      links:
            - phalcon

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example