version: '2.0'
services:

  db:
    build: ./db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwerty123
    volumes:
        - ./database:/var/lib/mysql

  adminer:
    build: ./adminer
    restart: always
    ports:
      - 8080:8080

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "6080:80"
    volumes:
      - ./public:/var/www/html/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    links:
      - phalcon

  phalcon:
    image: phalconphp/php-fpm:7-min
    restart: always
    volumes:
        - ./app:/var/www/html/app
        - ./public:/var/www/html/public
    ports:
          - "9000:9000"