version: '3.2'

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    links:
      - phalcon

  phalcon:
    image: phalconphp/php-fpm:7-min
    restart: always
    volumes:
        - ./app:/var/www/html/app
        - ./public:/var/www/html/public
    ports:
          - "9000:9000"