<h2>Sign up using this form</h2>

<?php echo $this->tag->form(array("signup/register", "class" => "form-group")); ?>
    <p>
        <label for="name">Name</label>
        <?php echo $this->tag->textField(array("name", "class" => "form-control")); ?>
    </p>
    <p>
        <label for="email">E-Mail</label>
        <?php echo $this->tag->textField(array("email", "class" => "form-control")); ?>
    </p>

    <p>
        <?php echo $this->tag->submitButton(array("Register", "class" => "btn btn-primary")); ?>
    </p>

</form>