<h2>Edit post</h2>

<form action="/post/update/<?php echo $posts->_id; ?>" method="post">
    <label for="title">Title</label>
    <?php echo $this->tag->textField(array("title", "class" => "form-control")); ?>

    <label for="body">Body</label>
    <?php echo $this->tag->textField(array("body", "class" => "form-control")); ?>

    <button class="btn" type="submit" name="save" >Save</button>
</form>